"""End to end on real AIS data: vessel timing in, agent decisions out.

    real observations ─▶ causal ETA ─▶ synthetic connection ─▶ risk event ─▶ agent

This is the first point where anything in LATCH touches real data, and it is
worth being precise about which half is which:

  Real        vessel positions, speeds and timestamps from October 2023
              Singapore AIS, and the arrival predictions derived from them by
              position and current speed alone.

  Ours        every connection. Which outbound service the cargo is booked to,
              the terminals, the box count, the cutoff. All generated by
              `connections.py` from frozen parameters.

So the *trigger* is real and the *stakes* are invented. A number produced here
measures whether the agent behaves sensibly on realistic vessel timing — not
how many containers PSA would have saved.

Legacy run:  uv run python scripts/run_historical.py --limit 50000

Causal Watcher retrospective synthetic connection benchmark:
  uv run python scripts/run_historical.py --mode watcher-eval
"""

import argparse
from collections import Counter
from dataclasses import replace
from datetime import timedelta
from pathlib import Path

from latch.cases import CaseRegistry
from latch.connections import ConnectionParams
from latch.events import RiskSeverity
from latch.historical_eval import (
    DEFAULT_CONNECTIONS_PER_QUOTA,
    DEFAULT_EVALUATION_HORIZONS,
    DEFAULT_SOURCE_CALL_LIMIT,
    HistoricalPopulationConfig,
    build_historical_benchmark_report,
    evaluate_historical_csv,
    file_sha256,
    historical_synthetic_config,
    replay_watcher_assessments,
    write_historical_benchmark_report,
)
from latch.llm import FakeModel, OllamaModel
from latch.replay import (
    ArrivalBoundary,
    ReplayConfig,
    iter_retrospectively_segmented_arrival_updates,
)
from latch.runner import AutoApprove, CustomerSilent, handle
from latch.trace import TraceStore
from latch.watcher import WatcherConfig, events_from_signals
from latch.synthetic import ProcessScenario

DEFAULT_CSV = (
    Path(__file__).resolve().parent.parent
    / "Data Inspection"
    / "Singapore_anonymized.csv"
)


def arrival_signals(csv_path: Path, config: ReplayConfig, limit: int | None):
    """Workstream A's Watcher-facing output, consumed directly.

    `CausalArrivalUpdate` already satisfies the `ArrivalSignal` protocol the
    adapter takes, so nothing converts between the two — the seam was built for
    exactly this and the payoff is that A owns crossing detection, reset
    confirmation and quality assessment, and B owns none of it.

    The *unfiltered* stream is deliberate. `iter_eligible_benchmark_updates`
    applies a retrospective quality filter, so a connection appears there only
    if the episode later turned out clean. Feeding B that stream would mean the
    agent only ever sees risks that resolved well, which is survivorship
    dressed up as a live feed.
    """
    for index, update in enumerate(
        iter_retrospectively_segmented_arrival_updates(csv_path, config)
    ):
        if limit is not None and index >= limit:
            break
        yield update


def _percentage(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.1%}"


def _hours(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.2f}h"


def _metric_line(label, metrics) -> str:
    counts = metrics.raw_connection_level
    rates = metrics.end_to_end_support.rates
    return (
        f"  {label:24} "
        f"TP {counts.tp:2} FP {counts.fp:2} TN {counts.tn:2} "
        f"FN {counts.fn:2} unavailable {counts.unavailable:2}  "
        f"end-to-end recall {_percentage(rates.recall):>6} "
        f"precision {_percentage(rates.precision):>6} "
        f"FAR {_percentage(rates.false_alarm_rate):>6} "
        f"F1 {_percentage(rates.f1):>6}"
    )


def run_watcher_evaluation(args, replay_config: ReplayConfig) -> None:
    """Score causal Watcher assessments without invoking the agent."""

    dataset_digest = file_sha256(args.csv)
    population_config = HistoricalPopulationConfig(
        source_call_limit=args.benchmark_call_limit
    )
    synthetic_config = historical_synthetic_config(
        dataset_sha256=dataset_digest,
        connections_per_quota=args.connections_per_quota,
    )
    watcher_config = WatcherConfig(
        warning_margin=timedelta(hours=args.watcher_warning_hours),
        reference_delay_threshold=timedelta(
            minutes=args.baseline_delay_minutes
        ),
        process_scenario=ProcessScenario(args.process_scenario),
    )
    result = evaluate_historical_csv(
        args.csv,
        replay_config=replay_config,
        population_config=population_config,
        synthetic_config=synthetic_config,
        watcher_config=watcher_config,
    )
    scenario_results = []
    for scenario in ProcessScenario:
        if scenario is watcher_config.process_scenario:
            scenario_results.append(result)
        else:
            scenario_results.append(
                replay_watcher_assessments(
                    result.population,
                    result.benchmark,
                    replace(watcher_config, process_scenario=scenario),
                )
            )
    horizons = tuple(
        timedelta(hours=value) for value in args.evaluation_horizons_hours
    )
    report = build_historical_benchmark_report(
        scenario_results,
        synthetic_config=synthetic_config,
        watcher_config=watcher_config,
        horizons=horizons,
    )
    if args.output is not None:
        write_historical_benchmark_report(report, args.output)

    selected = next(
        item
        for item in report.scenarios
        if item.process_scenario == watcher_config.process_scenario.value
    )
    composition = selected.composition
    counts = result.diagnostics

    print("retrospective synthetic connection benchmark")
    print("\nBenchmark composition")
    print(f"  selected scenario       {selected.process_scenario}")
    print(f"  process assumption      {selected.process_assumption_id}")
    print(f"  accepted PR #2 calls    {composition.accepted_pr2_calls:7,}")
    print(
        f"  bounded replay calls    {composition.bounded_replay_calls:7,}  "
        "(retrospectively constructed benchmark)"
    )
    print(f"  PR #3 candidates        {composition.pr3_candidate_calls:7,}")
    print(f"  synthetic connections   {composition.synthetic_connections:7,}")
    print(
        f"  valid outcomes          "
        f"{composition.connections_with_valid_retrospective_outcome:7,}"
    )
    print(
        f"  feasible/infeasible     {composition.feasible_synthetic_scenarios:3}/"
        f"{composition.infeasible_synthetic_scenarios:<3} synthetic scenarios"
    )
    print(
        f"  same/inter-terminal     {composition.same_terminal_connections:3}/"
        f"{composition.inter_terminal_connections:<3}"
    )
    print(
        "  transfer modes          "
        + ", ".join(f"{name}={count}" for name, count in composition.transfer_mode_breakdown)
    )
    print(
        f"  causal assessments      {counts.assessment_count:7,}  "
        f"activated UCIDs={counts.causally_activated_connection_count}"
    )
    severity = dict(counts.severity_distribution)
    print(
        "  Phase 2 diagnostics     "
        f"event-triggered unavailable={counts.unavailable_assessment_count}; "
        + ", ".join(
            f"{state}={severity.get(state, 0)}"
            for state in ("SAFE", "WATCH", "AT_RISK")
        )
        + f"; baseline alerts={counts.baseline_alert_count}"
    )

    print("\nAvailability")
    for horizon in selected.horizons:
        coverage = horizon.availability
        reason = ", ".join(
            f"{name}={count}" for name, count in coverage.unavailable_reasons
        ) or "none"
        print(
            f"  {horizon.horizon:5} {coverage.assessment_available:2}/"
            f"{coverage.total_benchmark_connections:<2} "
            f"({_percentage(coverage.availability_percentage)}) available; "
            f"unavailable={coverage.assessment_unavailable} ({reason})"
        )

    print("\nWatcher vs reference-delay baseline")
    print(
        "  Primary Watcher alert is WATCH or AT_RISK. Raw confusion counts "
        "are connection-level."
    )
    print(
        "  End-to-end rates shown below treat unavailable as no alert; common "
        "support is retained in JSON."
    )
    for horizon in selected.horizons:
        print(f"  {horizon.horizon}")
        print(_metric_line("Watcher", horizon.watcher))
        print(_metric_line("reference-delay", horizon.reference_delay_baseline))
        infeasible = horizon.paired_comparison.retrospectively_infeasible
        feasible = horizon.paired_comparison.retrospectively_feasible
        print(
            "    paired infeasible: "
            f"both={infeasible.both_alert} watcher-only={infeasible.watcher_only} "
            f"baseline-only={infeasible.baseline_only} neither={infeasible.neither}; "
            "feasible: "
            f"both={feasible.both_alert} watcher-only={feasible.watcher_only} "
            f"baseline-only={feasible.baseline_only} neither={feasible.neither}"
        )

    lead = selected.first_alert_lead_time
    print("\nFirst-alert lead time")
    for label, statistics in (
        ("Watcher", lead.watcher),
        ("reference-delay", lead.reference_delay_baseline),
    ):
        print(
            f"  {label:16} caught={statistics.caught_infeasible_connections} "
            f"missed={statistics.missed_infeasible_connections} "
            f"median={_hours(statistics.median_lead_time_h)} "
            f"p25={_hours(statistics.p25_lead_time_h)} "
            f"p75={_hours(statistics.p75_lead_time_h)}"
        )
    churn = selected.watcher_alert_churn
    print(
        f"  Watcher churn    median={churn.median_transitions_per_connection} "
        f"p90={churn.p90_transitions_per_connection} "
        f"zero={churn.zero_transition_connections}/{churn.connections} "
        f">{churn.diagnostic_threshold}={churn.above_threshold_connections}"
    )
    opportunity = selected.terminal_prevention_opportunity
    print(
        "  terminal-prevention opportunity "
        f"{opportunity.infeasible_with_transfer_feasible_without_transfer}/"
        f"{composition.infeasible_synthetic_scenarios} "
        f"({_percentage(opportunity.share_of_infeasible_scenarios)}); synthetic only"
    )

    print("\nScenario limitations")
    print(
        "  LOW, REFERENCE, and CONSERVATIVE use the same UCIDs/population; "
        "separate scenario scorecards are in JSON."
    )
    for limitation in report.limitations[:4]:
        print(f"  - {limitation}")
    if args.output is not None:
        print(f"\nDeterministic JSON written to {args.output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument(
        "--mode",
        choices=("legacy", "watcher-eval"),
        default="legacy",
        help="legacy keeps the original inbound-only agent run semantics",
    )
    parser.add_argument(
        "--limit", type=int, default=50_000, help="arrival updates to read from A"
    )
    parser.add_argument(
        "--max-agent-runs",
        type=int,
        default=25,
        help="cap agent invocations; the point is the mix, not the volume",
    )
    parser.add_argument("--model", choices=("fake", "local"), default="fake")
    parser.add_argument(
        "--benchmark-call-limit",
        type=int,
        default=DEFAULT_SOURCE_CALL_LIMIT,
        help="explicit deterministic accepted-call bound for watcher-eval",
    )
    parser.add_argument(
        "--connections-per-quota",
        type=int,
        default=DEFAULT_CONNECTIONS_PER_QUOTA,
        help="connections in each of four declared historical quota cells",
    )
    parser.add_argument("--watcher-warning-hours", type=float, default=2.0)
    parser.add_argument("--baseline-delay-minutes", type=float, default=15.0)
    parser.add_argument(
        "--process-scenario",
        choices=tuple(item.value for item in ProcessScenario),
        default=ProcessScenario.REFERENCE.value,
    )
    parser.add_argument(
        "--evaluation-horizons-hours",
        type=float,
        nargs="+",
        default=tuple(
            item.total_seconds() / 3600 for item in DEFAULT_EVALUATION_HORIZONS
        ),
        metavar="HOURS",
        help="fixed horizons before the retrospective synthetic cut-off",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="optional deterministic watcher-eval JSON report path",
    )
    args = parser.parse_args()

    if not args.csv.is_file() or args.csv.stat().st_size < 1_000:
        raise SystemExit(
            f"{args.csv} is missing or is still an LFS pointer. "
            "Run: git lfs install && git lfs pull"
        )

    config = ReplayConfig(boundary=ArrivalBoundary())
    if args.mode == "watcher-eval":
        run_watcher_evaluation(args, config)
        return

    params = ConnectionParams()

    signals = arrival_signals(args.csv, config, args.limit)
    severities: Counter[str] = Counter()
    registry = CaseRegistry()
    admitted: list[tuple] = []

    for event in events_from_signals(signals, params):
        severities[event.state.value] += 1
        decision = registry.admit(event)
        if decision.should_process and len(admitted) < args.max_agent_runs:
            admitted.append((event, decision))

    total = sum(severities.values())
    print(f"arrival updates read   {args.limit:,}  (workstream A)")
    print(f"risk events derived    {total:,}")
    for state in ("SAFE", "WATCH", "AT_RISK"):
        share = severities[state] / total if total else 0.0
        print(f"  {state:8} {severities[state]:7,}  {share:6.1%}")

    # The Watcher polls, so a connection under pressure emits an event every
    # cycle. Without the registry each one walks the whole ladder again and
    # every metric double-counts.
    print("\nadmission (one connection, one live case)")
    for name, count in registry.counts.items():
        if count:
            print(f"  {name:18} {count:7,}")
    duplicates = registry.counts["duplicate"] + registry.counts["already_resolved"]
    if total:
        print(f"  {'work avoided':18} {duplicates / total:7.1%} of events")

    if not admitted:
        print("\nNothing admitted in this slice.")
        return

    print(f"\nrunning {len(admitted)} admitted cases through the agent "
          f"({args.model})\n")
    store = TraceStore()
    for event, decision in admitted:
        client = (
            OllamaModel()
            if args.model == "local"
            else FakeModel(
                {
                    "triage": {"worth_deliberating": True, "reason": "scripted"},
                    "deliberation": {
                        "chosen_plan_id": "",
                        "ranking": [],
                        "rationale": "scripted",
                    },
                }
            )
        )
        outcome = handle(
            event,
            client=client,
            store=store,
            approvals=AutoApprove(),
            customer=CustomerSilent(),
        )
        # A superseding case references the trace it follows rather than
        # rewriting it. The earlier trace records what the agent decided at the
        # time and stays exactly as written — append-only means append-only.
        if decision.closes_previous:
            outcome.trace.observation(
                f"supersedes {decision.superseded_trace_id}: {decision.reason}"
            )
        registry.opened(event.connection_id, outcome.trace.trace_id)
        marker = "  (supersedes)" if decision.closes_previous else ""
        print(
            f"  {event.connection_id:20} {event.affected_boxes:4} boxes  "
            f"slack {event.current_plan_slack_hours:7.2f}h  -> "
            f"{outcome.resolution.value}{marker}"
        )

    metrics = store.metrics()
    rate = metrics["service_rate"]
    print(
        f"\nserved {metrics['served']}/{metrics['at_risk']} "
        f"({rate:.0%})" if rate is not None else "\nno at-risk outcomes to score"
    )
    print(
        "\nVessel timing is real October 2023 AIS. Every connection, terminal,\n"
        "box count and cutoff is generated from frozen parameters. This measures\n"
        "agent behaviour on realistic timing, not containers saved."
    )


if __name__ == "__main__":
    main()
