"""End to end on real AIS data: vessel timing in, agent decisions out.

    real observations ─▶ causal ETA ─▶ synthetic connection ─▶ risk event ─▶ agent

This is the first point where anything in LATCH touches real data, and it is
worth being precise about which half is which:

  Real        vessel positions, speeds and timestamps from October 2023
              Singapore AIS, and the arrival predictions derived from them by
              position and current speed alone.

  Ours        every connection. Which outbound service the cargo is booked to,
              the terminals, the box count, the cutoff. All generated by
              `connections.py` from frozen parameters.

So the *trigger* is real and the *stakes* are invented. A number produced here
measures whether the agent behaves sensibly on realistic vessel timing — not
how many containers PSA would have saved.

Run:  uv run python scripts/run_historical.py --limit 50000
"""

import argparse
from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from latch.cases import CaseRegistry
from latch.connections import ConnectionParams
from latch.events import RiskSeverity
from latch.llm import FakeModel, OllamaModel
from latch.replay import ArrivalBoundary, ReplayConfig, causal_eta, iter_replay_observations
from latch.runner import AutoApprove, CustomerSilent, handle
from latch.trace import TraceStore
from latch.watcher import events_from_signals

DEFAULT_CSV = (
    Path(__file__).resolve().parent.parent
    / "Data Inspection"
    / "Singapore_anonymized.csv"
)


@dataclass
class ArrivalSignalRow:
    """Built from main's replay primitives.

    Mirrors the shape of A's `CausalArrivalUpdate` without importing it, since
    that type currently lives only in an unmerged branch. The adapter takes a
    structural protocol, so A's richer version drops in with no change here.
    """

    call_id: str
    vessel_id: str
    observed_at: datetime
    predicted_arrival: datetime | None
    reference_arrival: datetime | None
    data_quality: str


def arrival_signals(csv_path: Path, config: ReplayConfig, limit: int | None):
    """Yield one signal per observation that supports a causal ETA.

    `reference_arrival` is the vessel's first eligible prediction — its
    original expected arrival. Everything after is measured against it, so a
    slipping vessel eats into slack rather than moving its own goalposts.
    """
    references: dict[str, datetime] = {}
    for index, observation in enumerate(iter_replay_observations(csv_path, config)):
        if limit is not None and index >= limit:
            break
        revision = causal_eta(
            observation, config.boundary, config.minimum_eta_speed_knots
        )
        if revision is None:
            continue
        reference = references.setdefault(
            observation.vessel_id, revision.estimated_arrival
        )
        yield ArrivalSignalRow(
            call_id=f"call_{observation.vessel_id}",
            vessel_id=observation.vessel_id,
            observed_at=observation.observed_at,
            predicted_arrival=revision.estimated_arrival,
            reference_arrival=reference,
            data_quality="degraded" if observation.quality_flags else "good",
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--limit", type=int, default=50_000, help="observations to read")
    parser.add_argument(
        "--max-agent-runs",
        type=int,
        default=25,
        help="cap agent invocations; the point is the mix, not the volume",
    )
    parser.add_argument("--model", choices=("fake", "local"), default="fake")
    args = parser.parse_args()

    if not args.csv.is_file() or args.csv.stat().st_size < 1_000:
        raise SystemExit(
            f"{args.csv} is missing or is still an LFS pointer. "
            "Run: git lfs install && git lfs pull"
        )

    config = ReplayConfig(boundary=ArrivalBoundary())
    params = ConnectionParams()

    signals = arrival_signals(args.csv, config, args.limit)
    severities: Counter[str] = Counter()
    registry = CaseRegistry()
    admitted: list[tuple] = []

    for event in events_from_signals(signals, params):
        severities[event.state.value] += 1
        decision = registry.admit(event)
        if decision.should_process and len(admitted) < args.max_agent_runs:
            admitted.append((event, decision))

    total = sum(severities.values())
    print(f"observations read      {args.limit:,}")
    print(f"risk events derived    {total:,}")
    for state in ("SAFE", "WATCH", "AT_RISK"):
        share = severities[state] / total if total else 0.0
        print(f"  {state:8} {severities[state]:7,}  {share:6.1%}")

    # The Watcher polls, so a connection under pressure emits an event every
    # cycle. Without the registry each one walks the whole ladder again and
    # every metric double-counts.
    print("\nadmission (one connection, one live case)")
    for name, count in registry.counts.items():
        if count:
            print(f"  {name:18} {count:7,}")
    duplicates = registry.counts["duplicate"] + registry.counts["already_resolved"]
    if total:
        print(f"  {'work avoided':18} {duplicates / total:7.1%} of events")

    if not admitted:
        print("\nNothing admitted in this slice.")
        return

    print(f"\nrunning {len(admitted)} admitted cases through the agent "
          f"({args.model})\n")
    store = TraceStore()
    for event, decision in admitted:
        client = (
            OllamaModel()
            if args.model == "local"
            else FakeModel(
                {
                    "triage": {"worth_deliberating": True, "reason": "scripted"},
                    "deliberation": {
                        "chosen_plan_id": "",
                        "ranking": [],
                        "rationale": "scripted",
                    },
                }
            )
        )
        outcome = handle(
            event,
            client=client,
            store=store,
            approvals=AutoApprove(),
            customer=CustomerSilent(),
        )
        # A superseding case references the trace it follows rather than
        # rewriting it. The earlier trace records what the agent decided at the
        # time and stays exactly as written — append-only means append-only.
        if decision.closes_previous:
            outcome.trace.observation(
                f"supersedes {decision.superseded_trace_id}: {decision.reason}"
            )
        registry.opened(event.connection_id, outcome.trace.trace_id)
        marker = "  (supersedes)" if decision.closes_previous else ""
        print(
            f"  {event.connection_id:20} {event.affected_boxes:4} boxes  "
            f"slack {event.current_plan_slack_hours:7.2f}h  -> "
            f"{outcome.resolution.value}{marker}"
        )

    metrics = store.metrics()
    rate = metrics["service_rate"]
    print(
        f"\nserved {metrics['served']}/{metrics['at_risk']} "
        f"({rate:.0%})" if rate is not None else "\nno at-risk outcomes to score"
    )
    print(
        "\nVessel timing is real October 2023 AIS. Every connection, terminal,\n"
        "box count and cutoff is generated from frozen parameters. This measures\n"
        "agent behaviour on realistic timing, not containers saved."
    )


if __name__ == "__main__":
    main()
